FROM ubuntu:18.04

RUN apt-get update && apt-get install -yq \
    software-properties-common \
    sudo \
    git \
    wget \
    curl \
    g++ \
    automake \
    make \
    cmake \
    xz-utils \
    openssh-server \
    python \
    clang-format-6.0 \
    libssl-dev libudev-dev

RUN add-apt-repository --yes ppa:openjdk-r/ppa && \
    apt-get -qq update && \
    apt-get install -y default-jre

RUN apt install cppcheck -y

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
